//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaMusical.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VentaMusicalDBEntities : DbContext
    {
        public VentaMusicalDBEntities()
            : base("name=VentaMusicalDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_Canciones> TB_Canciones { get; set; }
        public virtual DbSet<TB_Generos> TB_Generos { get; set; }
        public virtual DbSet<TB_GenerosMusicales> TB_GenerosMusicales { get; set; }
        public virtual DbSet<TB_Impuestos> TB_Impuestos { get; set; }
        public virtual DbSet<TB_Modulos> TB_Modulos { get; set; }
        public virtual DbSet<TB_Perfiles> TB_Perfiles { get; set; }
        public virtual DbSet<TB_PermisosPorModulo> TB_PermisosPorModulo { get; set; }
        public virtual DbSet<TB_TipoTarjetas> TB_TipoTarjetas { get; set; }
        public virtual DbSet<TB_Usuarios> TB_Usuarios { get; set; }
        public virtual DbSet<TB_VentaEncabezado> TB_VentaEncabezado { get; set; }
        public virtual DbSet<TB_VentaLinea> TB_VentaLinea { get; set; }
    }
}
