//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaMusical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PermisosPorModulo
    {
        public int IdPermiso { get; set; }
        public int IdPerfil { get; set; }
        public int IdModulo { get; set; }
    
        public virtual TB_Modulos TB_Modulos { get; set; }
        public virtual TB_Perfiles TB_Perfiles { get; set; }
    }
}
