//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaMusical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Usuarios()
        {
            this.TB_VentaEncabezado = new HashSet<TB_VentaEncabezado>();
        }
    
        public string NumeroIdentificacion { get; set; }
        public string Nombre { get; set; }
        public int IdGenero { get; set; }
        public string Correo { get; set; }
        public int IdTarjeta { get; set; }
        public string NumeroTarjeta { get; set; }
        public string Contrasena { get; set; }
        public int IdPerfil { get; set; }
    
        public virtual TB_Generos TB_Generos { get; set; }
        public virtual TB_Perfiles TB_Perfiles { get; set; }
        public virtual TB_TipoTarjetas TB_TipoTarjetas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_VentaEncabezado> TB_VentaEncabezado { get; set; }
    }
}
