//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaMusical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_VentaEncabezado
    {
        public int NumeroFactura { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Total { get; set; }
        public string NumeroIdentificacion { get; set; }
        public int IdFormaPago { get; set; }
    
        public virtual TB_FormasDePago TB_FormasDePago { get; set; }
        public virtual TB_Usuarios TB_Usuarios { get; set; }
        public virtual TB_VentaLinea TB_VentaLinea { get; set; }
    }
}
