//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaMusical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_VentaLinea
    {
        public int NumeroFactura { get; set; }
        public int Linea { get; set; }
        public int CodigoCancion { get; set; }
        public decimal Precio { get; set; }
        public int IdImpuesto { get; set; }
        public int Cantidad { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Total { get; set; }
    
        public virtual TB_Canciones TB_Canciones { get; set; }
        public virtual TB_Impuestos TB_Impuestos { get; set; }
        public virtual TB_VentaEncabezado TB_VentaEncabezado { get; set; }
    }
}
